a = input('Digite algo: ')
print('Apenas maiúsculas?', a.isupper())
print('Apenas minúsculas?', a.islower())
print('É um número?', a.isnumeric())
print('Apenas letras?', a.isalpha())
print('Apenas números?', a.isnumeric())
print('Contém letras e números?', a.isalnum())
print('Apenas espaços?', a.isspace())
print('Está capitalizada?', a.istitle())